version: '2'

services:
  teamcity-db:
    image: postgres:9.4
    environment:
        - POSTGRES_USER=teamcity
        - POSTGRES_PASSWORD=supersecure
    volumes:
        - /volumes/postgresql/data:/var/lib/postgresql/data

  teamcity-server:
    build: docker-alpine-teamcity-server
    ports:
        - 8111:8111
    volumes:
        - /volumes/teamcity:/var/lib/teamcity

  teamcity-agent:
    build: docker-alpine-teamcity-agent
    restart: on-failure
    environment:
        - TEAMCITY_SERVER=http://teamcity-server:8111
    volumes:
        - /volumes/buildagent/conf:/opt/agent/conf
        - /var/run/docker.sock:/var/run/docker.sock
        - ~/.aws:/root/.aws
        - ~/.docker:/root/.docker
