teamcity-db:
    image: postgres
    environment:
        - POSTGRES_USER=teamcity
        - POSTGRES_PASSWORD=supersecure
    volumes:
        - /volumes/postgresql/data:/var/lib/postgresql/data

teamcity-server:
    build: docker-alpine-teamcity-server
    links:
        - teamcity-db:teamcity-db
    ports:
        - 8111:8111
    volumes:
        - /volumes/teamcity:/var/lib/teamcity

teamcity-agent:
    build: docker-alpine-teamcity-agent
    restart: on-failure
    links:
        - teamcity-server:teamcity-server
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
