version: '2'

services:
  teamcity-agent:
    build: .
    restart: unless-stopped
    env_file: teamcity-agent.env
    ports:
      - 9090:9090
    volumes:
        - /volumes/buildagent/conf:/opt/agent/conf
        - /var/run/docker.sock:/var/run/docker.sock
        - ~/.aws:/root/.aws
        - ~/.docker:/root/.docker
